### ISSUE TITLE
Failed to activate the nuclide-format-js package

### ISSUE THREAD

**Issue by markbye** [facebook-atom/nuclide-format-js#69]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [nuclide-format-js](https://github.com/facebook-atom/nuclide-format-js) package 0.0.43

### Stack Trace

Failed to activate the nuclide-format-js package

```
At Cannot add to an already disposed UniversalDisposable!

Error: Cannot add to an already disposed UniversalDisposable!
    at UniversalDisposable.add (/packages/nuclide/modules/nuclide-commons/UniversalDisposable.js:24:13)
    at Activation.consumeOrganizeRequiresService (/packages/nuclide/pkg/nuclide-js-imports-client/lib/main.js:184:31)
    at /packages/nuclide/modules/nuclide-commons-atom/createPackage.js:51:38)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.provide (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/service-hub.js:30:26)
    at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app/src/package.js:448:77)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:258:22)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:227:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:220:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:217:40)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:695:42)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:535:35
    at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:17)
    at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:351:17
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:220:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

### Commands

```
  5x -3:51.3.0 core:confirm (input.hidden-input)
     -3:45 editor:consolidate-selections (input.hidden-input)
     -3:45 core:cancel (input.hidden-input)
  2x -2:58.6.0 core:backspace (input.hidden-input)
     -2:56 core:confirm (input.hidden-input)
     -2:37.3.0 core:save (input.hidden-input)
     -2:36.1.0 core:undo (input.hidden-input)
     -2:23.9.0 core:save (input.hidden-input)
     -2:22.7.0 core:undo (input.hidden-input)
     -1:48.6.0 core:save (input.hidden-input)
     -1:47.1.0 core:undo (input.hidden-input)
     -1:44.2.0 core:save-as (input.hidden-input)
     -1:12.2.0 core:undo (input.hidden-input)
     -0:58.8.0 core:select-all (input.hidden-input)
     -0:56.3.0 code-format:format-code (div.line)
     -0:07.7.0 core:select-all (input.hidden-input)
```

### Non-Core Packages

```
atom-standard-format 0.2.0 
formatter-json 1.0.1 
formatter-tidy 1.0.1 
highlight-selected 0.13.1 
jsformat 0.9.3 
minimap 4.29.7 
minimap-highlight-selected 4.6.1 
nuclide 0.272.0 
nuclide-format-js 0.0.43 
react 0.17.0 
react-native-snippets 0.3.0 
```

**Comment by xlliang** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.4
**Thrown From**: [nuclide-format-js](https://github.com/facebook-atom/nuclide-format-js) package 0.0.45


### Stack Trace

Failed to activate the nuclide-format-js package

```
At Cannot add to an already disposed UniversalDisposable!

Error: Cannot add to an already disposed UniversalDisposable!
    at UniversalDisposable.add (/packages/nuclide/modules/nuclide-commons/UniversalDisposable.js:33:13)
    at Activation.consumeOrganizeRequiresService (/packages/nuclide/pkg/nuclide-js-imports-client/lib/main.js:157:31)
    at /packages/nuclide/modules/nuclide-commons-atom/createPackage.js:62:34)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.provide (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/service-hub.js:30:26)
    at Package.activateServices (/Applications/Atom.app/Contents/Resources/app/src/package.js:397:75)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:233:20)
    at measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:206:33)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:88:25)
    at activationPromise.Promise (/Applications/Atom.app/Contents/Resources/app/src/package.js:200:20)
    at Promise (<anonymous>)
    at Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:695:42)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:491:35
    at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:267:15)
    at ChildProcess.process.on (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:297:15)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
     -9:58.2.0 core:select-all (input.hidden-input)
  2x -9:55.1.0 code-format:format-code (div.line)
     -6:53.8.0 nuclide-settings:toggle (input.hidden-input)
  2x -4:26.1.0 core:save (input.hidden-input)
     -4:11.1.0 nuclide-health:toggle (input.hidden-input)
     -4:05.2.0 nuclide-settings:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui.find-visible)
  2x -3:51.9.0 window:increase-font-size (input.hidden-input)
  8x -3:30 core:backspace (input.hidden-input)
     -3:07.6.0 settings-view:open (input.hidden-input)
  2x -2:57.3.0 core:confirm (input.hidden-input)
     -2:30.1.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
file-icons 2.1.19 
highlight-selected 0.13.1 
language-babel 2.85.0 
language-graphql 0.10.1 
language-haskell 1.17.6 
language-ini 1.19.0 
language-kotlin 0.5.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.12 
language-scala 1.1.9 
language-swift 0.5.0 
language-thrift 1.0.2 
nuclide 0.301.1 
nuclide-format-js 0.0.45 
set-syntax 0.4.0 
sort-lines 0.18.0 
tool-bar 1.1.7 
```

**Comment by idotial** [comment]
are you fix it? i meet this problem now

**Comment by zhangzhibinhi** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.29.0 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.13.6
**Thrown From**: [nuclide-format-js](https://github.com/facebook-atom/nuclide-format-js) package 0.0.47


### Stack Trace

Failed to activate the nuclide-format-js package

```
At Cannot add to an already disposed UniversalDisposable!

Error: Cannot add to an already disposed UniversalDisposable!
    at UniversalDisposable.add (/packages/nuclide/modules/nuclide-commons/UniversalDisposable.js:36:13)
    at Activation.consumeOrganizeRequiresService (/packages/nuclide/pkg/nuclide-js-imports-client/lib/main.js:290:31)
    at /packages/nuclide/modules/nuclide-commons-atom/createPackage.js:64:34)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.provide (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/service-hub.js:30:26)
    at Package.activateServices (/Applications/Atom.app/Contents/Resources/app/src/package.js:397:75)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:233:20)
    at measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:206:33)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:88:25)
    at activationPromise.Promise (/Applications/Atom.app/Contents/Resources/app/src/package.js:200:20)
    at new Promise (<anonymous>)
    at Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:695:42)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:491:35
    at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:267:15)
    at bufferStream (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:288:15)
    at Socket.stream.on (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:164:13)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
```

### Commands

```
 35x -8:38.2.0 core:backspace (input.hidden-input)
     -0:17.5.0 nuclide-task-runner:toggle-toolbar-visibility (div.panels-item)
     -0:13 application:add-project-folder (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
docblockr 0.13.7 
file-icons 2.1.24 
highlight-selected 0.14.0 
hyperclick 0.1.5 
language-babel 2.85.0 
language-graphql 0.10.1 
language-haskell 1.17.8 
language-ini 1.20.0 
language-kotlin 0.5.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.12 
language-scala 1.1.9 
language-swift 0.5.0 
language-thrift 1.0.2 
nuclide 0.339.0 
nuclide-format-js 0.0.47 
react 0.18.0 
set-syntax 0.4.0 
sort-lines 0.18.0 
tool-bar 1.1.7 
```
